name: README Watch

on:
  push:
    paths:
      - "README.md"

jobs:
  watch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: README changed
        run: |
          echo "README.md が更新されました！"
          date
